server:
  port: 8761

spring:
  application:
    name: SERVICE_REGISTRY
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
