version: '3'

services:

  serviceregistry:
    build:
      context: service-registry
      dockerfile: Dockerfile
    image: 'tuhin47/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
    networks:
      - backend

  configserver:
    build:
      context: configserver
      dockerfile: Dockerfile
    image: 'tuhin47/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configserver:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
    networks:
      - backend

  apigateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    image: 'tuhin47/apigateway:0.0.1'
    container_name: apigateway
    ports:
      - '9090:9090'
      - '19090:19090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - ZIPKIN_URL=http://zipkin:9411/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - configserver
      - zipkin
      - redis
      - serviceregistry
      - orderservice
      - authservice
      - paymentservice
    networks:
      - backend


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
#      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
#      - SCRIBE_ENABLED=false
#      - SELF_TRACING_ENABLED=true
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend


  authservice:
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: 'tuhin47/authservice:0.0.1'
    container_name: authservice
    ports:
      - '7777:7777'
      - '17777:17777'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111111
      - MYSQL_DB=userdb
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      - backend


  productservice:
    build:
      context: productservice
      dockerfile: Dockerfile
    image: 'tuhin47/productservice:0.0.1'
    container_name: productservice
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111111
      - ZIPKIN_URL=http://zipkin:9411/
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      zipkin:
        condition: service_healthy
    networks:
      - backend

  orderservice:
    build:
      context: orderservice
      dockerfile: Dockerfile
    image: 'tuhin47/orderservice:0.0.1'
    container_name: orderservice
    ports:
      - '8082:8082'
      - '18082:18082'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111111
      - ZIPKIN_URL=http://zipkin:9411/
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=18082,server=y,suspend=y
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      zipkin:
        condition: service_healthy
    networks:
      - backend


  paymentservice:
    build:
      context: paymentservice
      dockerfile: Dockerfile
    image: 'tuhin47/paymentservice:0.0.1'
    container_name: paymentservice
    ports:
      - '8083:8083'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111111
      - ZIPKIN_URL=http://zipkin:9411/
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      zipkin:
        condition: service_healthy
    networks:
      - backend


  database:
    container_name: database
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=extra
      - MYSQL_PASSWORD=extra
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DB=userdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


networks:
  backend:
    driver: bridge

volumes:
  db-data: