version: '3'

services:

 #Front-end Angular boilerplate
  boilerplate:
    build:
      context: ./angular-boilerplate
      dockerfile: Dockerfile
      args:
       - ENVIRONMENT
       - API_BASE
       - OAUTH_REDIRECT_URL
    container_name: boilerplate
    image: 'tuhin47/boilerplate:prod'
    ports:
      - 4200:80
    links:
      - apigateway
      - authservice
    networks:
      - backend

  serviceregistry:
    build:
      context: service-registry
      dockerfile: ../Dockerfile
    image: 'tuhin47/serviceregistry:prod'
    ports:
      - 8761:8761
    networks:
      - backend

  configserver:
    build:
      context: configserver
      dockerfile: ../Dockerfile
    image: tuhin47/configserver:prod
    ports:
      - 9296:9296
    environment:
      - EUREKA_SERVER_ADDRESS
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configserver:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
    networks:
      - backend

  apigateway:
    build:
      context: apigateway
      dockerfile: ../Dockerfile
    image: 'tuhin47/gateway:prod'
    container_name: apigateway
    ports:
      - 9090:9090
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - ZIPKIN_URL
      - REDIS_URL=redis://redis:6379
    depends_on:
      - configserver
      - zipkin
      - redis
      - serviceregistry
      - orderservice
      - authservice
      - paymentservice
    networks:
      - backend


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
#      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
#      - SCRIBE_ENABLED=false
#      - SELF_TRACING_ENABLED=true
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend


  authservice:
    build:
      context: spring-boot-oauth2-social-login
      dockerfile: ../Dockerfile
    image: 'tuhin47/authservice:prod'
    ports:
      - 7777:7777
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB=userdb
      - CLIENT_ID
      - CLIENT_SECRET
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - backend


  productservice:
    build:
      context: productservice
      dockerfile: ../Dockerfile
    image: 'tuhin47/productservice:prod'
    ports:
      - 8081:8081
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - ZIPKIN_URL
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - backend

  orderservice:
    build:
      context: orderservice
      dockerfile: ../Dockerfile
    image: 'tuhin47/orderservice:prod'
    ports:
      - 8082:8082
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - ZIPKIN_URL
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - backend

  chatservice:
    build:
      context: chat-service
      dockerfile: ../Dockerfile
    image: 'tuhin47/chatservice:prod'
    ports:
      - 8084:8084
    environment:
      - CONFIG_SERVER_URL
      - EUREKA_SERVER_ADDRESS
      - MONGO_AUTHENTICATION_DATABASE
      - MONGO_DATABASE
      - MONGO_HOST
      - MONGO_PASSWORD
      - MONGO_PORT
      - MONGO_USERNAME
      - ZIPKIN_URL
    depends_on:
      mongo:
        condition: service_healthy
      configserver:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - backend


  paymentservice:
    build:
      context: paymentservice
      dockerfile: ../Dockerfile
    image: 'tuhin47/paymentservice:prod'
    ports:
      - 8083:8083
    environment:
      - MYSQL_DB=paymentdb
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - ZIPKIN_URL
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - backend

  database:
    container_name: database
    image: 'mysql:latest'
    ports:
      - $MYSQL_PORT:3306
    restart: always
    environment:
      - MYSQL_USER=extra
      - MYSQL_PORT
      - MYSQL_PASSWORD=extra
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB=userdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
  mongo-volume:
    driver: local
