services:

  apigateway:
    build:
      context: apigateway
      dockerfile: ../Dockerfile
    image: tuhin47/gateway:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - "9090:9090"
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - TRACING_URL
      - REDIS_URL
      - ALLOWED_ORIGINS
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - DOMAIN_SCHEME
      - DOMAIN_NAME
      - DOMAIN_PORT
      - KC_HTTP_RELATIVE_PATH
      - LOG_PATH=/tmp/logs/apigateway/
    depends_on:
      configserver:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy
      serviceregistry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://apigateway:9090/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  authservice:
    build:
      context: authservice
      dockerfile: ../Dockerfile
    image: tuhin47/authservice:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB=userdb
      - CLIENT_ID
      - CLIENT_SECRET
      - TRACING_URL
      - REDIS_URL
      - AXON_SERVER_URL
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - DOMAIN_SCHEME
      - DOMAIN_NAME
      - DOMAIN_PORT
      - KC_HTTP_RELATIVE_PATH
      - LOG_PATH=/tmp/logs/authservice/
      - SPRING_MAIL_HOST
      - SPRING_MAIL_PORT
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://authservice:7777/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      keycloak:
        condition: service_healthy
      mailcatcher:
        condition: service_started
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - backend

  chatservice:
    build:
      context: chat-service
      dockerfile: ../Dockerfile
    profiles:
      - all
    image: tuhin47/chatservice:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - "8084:8084"
    environment:
      - CONFIG_SERVER_URL
      - EUREKA_SERVER_ADDRESS
      - MONGO_AUTHENTICATION_DATABASE
      - MONGO_DATABASE
      - MONGO_HOST
      - MONGO_PASSWORD
      - MONGO_PORT
      - MONGO_USERNAME
      - TRACING_URL
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - LOG_PATH=/tmp/logs/chatservice/
    depends_on:
      mongo:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - backend

  configserver:
    build:
      context: configserver
      dockerfile: ../Dockerfile
    image: tuhin47/configserver:${IMAGE_TAG}
    ports:
      - "9296:9296"
    environment:
      - EUREKA_SERVER_ADDRESS
      - LOG_PATH=/tmp/logs/configserver/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configserver:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  orderservice:
    build:
      context: orderservice
      dockerfile: ../Dockerfile
    image: tuhin47/orderservice:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB=orderdb
      - TRACING_URL
      - REDIS_URL
      - AXON_SERVER_URL
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - DOMAIN_SCHEME
      - DOMAIN_NAME
      - DOMAIN_PORT
      - KC_HTTP_RELATIVE_PATH
      - LOG_PATH=/tmp/logs/orderservice/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://orderservice:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - backend

  paymentservice:
    build:
      context: paymentservice
      dockerfile: ../Dockerfile
    image: tuhin47/paymentservice:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - "8083:8083"
    environment:
      - MYSQL_DB=paymentdb
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TRACING_URL
      - REDIS_URL
      - AXON_SERVER_URL
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - DOMAIN_SCHEME
      - DOMAIN_NAME
      - DOMAIN_PORT
      - KC_HTTP_RELATIVE_PATH
      - LOG_PATH=/tmp/logs/paymentservice/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://paymentservice:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - backend

  productservice:
    build:
      context: productservice
      dockerfile: ../Dockerfile
    image: tuhin47/productservice:${IMAGE_TAG}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_URL
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB=productdb
      - TRACING_URL
      - REDIS_URL
      - NOAUTH_ENABLE
      - LOGSTASH_HOST
      - SPRING_PROFILES_ACTIVE
      - DOMAIN_SCHEME
      - DOMAIN_NAME
      - DOMAIN_PORT
      - KC_HTTP_RELATIVE_PATH
      - LOG_PATH=/tmp/logs/productservice/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://productservice:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - backend

  serviceregistry:
    build:
      context: service-registry
      dockerfile: ../Dockerfile
    image: tuhin47/serviceregistry:${IMAGE_TAG}
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/registry/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    environment:
      - EUREKA_PATH
      - LOG_PATH=/tmp/logs/serviceregistry/


  build_all:
    image: maven:3.9-eclipse-temurin-22
    environment:
      - MAVEN_REPO
      - PROJECT_PATH
    profiles:
      - Build
    working_dir: /app
    volumes:
      - $PROJECT_PATH/:/app
      - $MAVEN_REPO:/root/.m2/repository
    command: mvn clean package -DskipTests

  axonserver:
    extends:
      service: axonserver
      file: docker-compose.common.yml

  boilerplate:
    extends:
      file: docker-compose.common.yml
      service: boilerplate

  database:
    extends:
      service: database
      file: docker-compose.common.yml

  elasticsearch:
    extends:
      service: elasticsearch
      file: docker-compose.elk.yml

  jaeger-service:
    extends:
      file: docker-compose.common.yml
      service: jaeger-service

  keycloak:
    extends:
      file: docker-compose.common.yml
      service: keycloak

  kibana:
    depends_on:
      - elasticsearch
    extends:
      service: kibana
      file: docker-compose.elk.yml

  localstack:
    extends:
      service: localstack
      file: docker-compose.common.yml

  logstash:
    depends_on:
      - elasticsearch
    extends:
      service: logstash
      file: docker-compose.elk.yml
  proxy:
    depends_on:
      serviceregistry:
        condition: service_started
      keycloak:
        condition: service_started
      apigateway:
        condition: service_started
    extends:
      file: docker-compose.common.yml
      service: proxy
  mailcatcher:
    extends:
      service: mailcatcher
      file: docker-compose.common.yml

  mongo:
    extends:
      service: mongo
      file: docker-compose.common.yml

  redis:
    extends:
      service: redis
      file: docker-compose.common.yml

  testservice:
    extends:
      service: testservice
      file: docker-compose.common.yml

  tracing:
    extends:
      file: docker-compose.common.yml
      service: tracing

networks:
  backend:
    driver: bridge

volumes:
  db-data:
  mongo-volume:
    driver: local
  axonserver-data:
    driver: local
  axonserver-events:
    driver: local
  axonserver-config:
    driver: local
  esdata:
    driver: local
