eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # https://stackoverflow.com/a/50523578/7499069
  servlet:
    multipart:
      location: /data/upload_tmp
  redis:
    host: ${REDIS_HOST:localhost}
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411/}

axon:
  axonserver:
    servers: ${AXON_SERVER_URL:localhost:8124}

app:
  version: @project.version@
  config:
    qrIssuer : tuhin47
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorization request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris: http://localhost:4200/auth/login,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect

logging:
  level:
    com: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type: DEBUG