spring:
  zipkin:
    enabled: false

axon:
  axonserver:
    enabled: false

app:
  config:
    noAuth: true

logging:
  level:
    com: INFO
    me:
      tuhin47: DEBUG
    org:
      springframework.orm.jpa: INFO
      springframework.transaction: DEBUG
      springframework: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG
