server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${MYSQL_DB:userdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
          facebook:
            clientId: <your-client-id>
            clientSecret: <your-client-secret>
          github:
            clientId: <your-client-id>
            clientSecret: <your-client-secret>
          linkedin:
            clientId: <your-client-id>
            clientSecret: <your-client-secret>
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: 'r_liteprofile, r_emailaddress'
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-name: Linkedin
            provider: linkedin
        provider:
          facebook:
            user-info-uri: 'https://graph.facebook.com/me?fields'
          linkedin:
            authorization-uri: 'https://www.linkedin.com/oauth/v2/authorization'
            token-uri: 'https://www.linkedin.com/oauth/v2/accessToken'
            user-info-uri: 'https://api.linkedin.com/v2/me'
            user-name-attribute: id
linkedin:
  email-address-uri: 'https://api.linkedin.com/v2/emailAddress?q'

springfox:
  documentation:
    open-api:
      v3:
        path: /auth/v3/api-docs