server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${MYSQL_DB:orderdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true


springdoc:
  api-docs:
    path: /order/v3/api-docs