server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${MYSQL_DB:orderdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10 # buffer size 10
        failure-rate-threshold: 50 #
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true # half open enabled
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10 # record the outcome of calls when the CircuitBreaker is closed
        sliding-window-type: COUNT_BASED # the type of the sliding window

feign:
  client:
    config:
      default:
        errorDecoder: me.tuhin47.orderservice.external.decoder.CustomErrorDecoder
      stores:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        requestInterceptors:
          - me.tuhin47.orderservice.config.FeignConfig

springfox:
  documentation:
    open-api:
      v3:
        path: /order/v3/api-docs