server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:paymentdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

springdoc:
  api-docs:
    path: /payment/v3/api-docs