server:
  port: 8081

spring:
  flyway:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${MYSQL_DB:productdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/${MYSQL_DB:productdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none

springfox:
  documentation:
    open-api:
      v3:
        path: /product/v3/api-docs