spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
    activate:
      on-profile:
        - elk
        - default
        - dev