configserver:
  import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: ${configserver.import}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}