issuer: ${KC_HOST:http://gateway:8080/sso}/realms/baeldung
client-id: baeldung-confidential
client-secret: secret

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      client:
        provider:
          baeldung:
            issuer-uri: ${issuer}
        registration:
          baeldung:
            provider: baeldung
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid,profile,email,offline_access

authorities-mapping:
  issuers:
    - uri: ${issuer}
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
origins:
  allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:4200}
management:
  otlp:
    tracing:
      endpoint: ${TRACING_URL:http://127.0.0.1:4317}
      transport: grpc
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
        # include: "health,info"
  endpoint:
    health:
      show-details: always

