apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-app
spec:
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      containers:
        - name: auth-service-app
          image: tuhin47/authservice:0.3.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7777
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url
            - name: NOAUTH_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: noauth_enable
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: client-secret
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-cm
                  key: redis-url
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: zipkin-cm
                  key: zipkin_url
            - name: AXON_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: axon-cm
                  key: axon_server_url


---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  selector:
    app: auth-service-app
  ports:
    - port: 80
      targetPort: 7777