apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
        - name: product-service-app
          image: tuhin47/productservice:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url
            - name: NOAUTH_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: noauth_enable
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-cm
                  key: redis-host
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: zipkin-cm
                  key: zipkin_url
            - name: AXON_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: axon-cm
                  key: axon_server_url


---

apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service-app
  ports:
    - port: 80
      targetPort: 8081