worker_processes auto;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /var/cache/nginx/client_temp;
    proxy_temp_path       /var/cache/nginx/proxy_temp;
    fastcgi_temp_path     /var/cache/nginx/fastcgi_temp;
    uwsgi_temp_path       /var/cache/nginx/uwsgi_temp;
    scgi_temp_path        /var/cache/nginx/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  60s;
    keepalive_requests 1000;

    gzip            on;
    gzip_vary       on;
    gzip_proxied    no-cache no-store private expired auth;
    gzip_min_length 10240;
    gzip_types
    application/javascript
    application/json
    font/woff2
    text/css
    text/plain;

    proxy_http_version 1.1;
    proxy_set_header Connection "Keep-Alive";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-CSRF-TOKEN $http_x_csrf_token;
    proxy_set_header Cookie $http_cookie;

    proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
    proxy_next_upstream_tries 3;
    proxy_next_upstream_timeout 10s;

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    proxy_buffer_size 16k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;

    upstream keycloak_upstream {
        server keycloak:8080;
        keepalive 32;
    }

    upstream apigateway_upstream {
        server apigateway:9090;
        keepalive 32;
    }

    server {
        listen 80;

        location / {
            gzip_static on;
            proxy_pass http://apigateway_upstream;
        }

        location /sso {
            proxy_pass http://keycloak_upstream;
        }

        location /registry {
            proxy_pass http://serviceregistry:8761;
        }
    }
}
