
events {
    worker_connections 1024;
}

http {
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log  /var/log/nginx/access.log  main;
  sendfile        on;
  keepalive_timeout  65;

  gzip            on;
  gzip_static     on;
  gzip_vary       on;
  gzip_proxied    no-cache no-store private expired auth;
  gzip_min_length 10240;
  gzip_types
  application/javascript
  application/json
  font/woff2
  text/css
  text/plain;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
  proxy_next_upstream_tries 3;
  proxy_next_upstream_timeout 10s;

  proxy_connect_timeout 60s;
  proxy_send_timeout 60s;
  proxy_read_timeout 60s;
  proxy_buffer_size 16k;
  proxy_buffers 4 32k;
  proxy_busy_buffers_size 64k;

   upstream keycloak_upstream {
        server keycloak:8080;
        keepalive 32;
        keepalive_requests 1000;
        keepalive_timeout 60s;
    }
    upstream apigateway_upstream {
        server apigateway:9090;
        keepalive 32;
        keepalive_requests 1000;
        keepalive_timeout 60s;
    }
    server {
        listen 80;

        location / {
          proxy_pass http://apigateway_upstream;
        }

        location /auth {
            proxy_pass http://keycloak_upstream;
        }

        location /registy {
           proxy_pass http://serviceregistry:8761;
        }

    }

}
