spring:
  datasource:
    url: jdbc:h2:mem:payment
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: PAYMENT-SERVICE


jwt:
  secret: mySecretKey