server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
#        git:
#          uri: https://github.com/tuhin47/springconfigs
#          clone-on-start: true
#          username: ${GITHUB_USER}
#          password: ${GITHUB_TOKEN}


app:
  version: @project.version@

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
