###

POST http://localhost:7777/auth/signup
Content-Type: application/json

{
    "displayName": "Towhidul",
    "email": "sample123@gmail.com",
    "password": "123456",
    "matchingPassword": "123456",
    "socialProvider": "LOCAL"
}

###

POST http://localhost:7777/auth/signin
Accept: application/json
Content-Type: application/json

{
    "email": "sample123@gmail.com",
    "password": "123456"
}

> {%
    client.global.set("token", response.body.accessToken);
%}


###
GET http://localhost:7777/auth/user/me
accept: */*
Authorization: Bearer {{token}}

###

POST http://localhost:8081/product
accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0dWhpbjQ3LmNvbSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsImlhdCI6MTY4OTcwNDQ2MSwiZXhwIjoxNjkwNTY4NDYxfQ.HQ0enIoInbAZX7582EQa2FT_ulUGX0JUn4aasTrtNkvC1XBSQaE8bhjWX8coCp90bjswrPu1uMYSHeJL9fhTHg
Content-Type: application/json

{
    "name": "Pro 1",
    "price": 20,
    "quantity": 20
}

###

POST http://localhost:8082/order
accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0dWhpbjQ3LmNvbSIsImF1dGhlbnRpY2F0ZWQiOnRydWUsImlhdCI6MTY4OTcwNDQ2MSwiZXhwIjoxNjkwNTY4NDYxfQ.HQ0enIoInbAZX7582EQa2FT_ulUGX0JUn4aasTrtNkvC1XBSQaE8bhjWX8coCp90bjswrPu1uMYSHeJL9fhTHg
Content-Type: application/json

{
    "paymentMode": "DEBIT_CARD",
    "productId": 2,
    "quantity": 1,
    "totalAmount": 10
}

###

POST http://localhost:99993/
Content-Type: application/json

{
    "name": "pro1",
    "price": 111,
    "quantity": 10
}

###

POST http://localhost:7777/actuator/loggers/{{package}}
Accept: application/json
Content-Type: application/json

{
    "configuredLevel": "{{logLevel}}",
    "effectiveLevel": "{{logLevel}}"
}

###
GET http://localhost:7777/auth/all

###

POST http://localhost:7777/actuator/refresh
Accept: application/json