spring:
  mail:
    host: ${SPRING_MAIL_HOST:127.0.0.1}
    port: ${SPRING_MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  task:
    scheduling:
      pool:
        size: 2
application:
  theme:
    color: black