server:
  port: 8765
  
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}