spring:
  application:
    name: AWS-SERVICES
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/aws?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    pool:
      enabled: true
      initial-size: 5
    properties:
      useUnicode: true
      characterEncoding: utf-8
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/aws
    password: root
    user: root

config:
  aws:
    region: us-east-1
    access-key: localstack
    secret-key: localstack
    url: http://127.0.0.1:4566
    s3:
      bucket-name: spring47-s3
    sns:
      topic-name: spring47-item-info-topic
    sqs:
      queue-name: spring47-item-info-queue

cloud:
  aws:
    rds:
      enabled: false
    stack:
      auto: false
    region:
      static: us-east-1