version: '2'
services:
    oidc-login:
        container_name: oidc-login
        build:
            context: ./
            dockerfile: Dockerfile
        image: 'tuhin47/oidc-login'
        ports:
            - 8765:8765
        networks:
            - spring-cloud-network
        environment:
            - CLIENT_ID
            - CLIENT_SECRET
#    product-server:
#        container_name: product-server
#        build:
#            context: docker-product-server
#            dockerfile: Dockerfile
#        image: product-server:latest
#        ports:
#            - 19999:9999
#        networks:
#            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge