server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:orderdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

#  sleuth:
#    scheduled:
#      skip-pattern: (^cleanup.*|.+favicon.*)

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10 # buffer size 10
        failure-rate-threshold: 50 #
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true # half open enabled
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10 # record the outcome of calls when the CircuitBreaker is closed
        sliding-window-type: COUNT_BASED # the type of the sliding window

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


feign:
  client:
    config:
      stores:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        requestInterceptors:
          - com.microservice.orderservice.config.FeignConfig
