spring:
  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: ORDER-SERVICE

jwt:
  secret: mySecretKey