issuer: ${DOMAIN_SCHEME:http}://${DOMAIN_NAME:gateway}:${DOMAIN_PORT:8888}/${KC_HTTP_RELATIVE_PATH:sso}
spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}