spring:
  application:
    name: CHAT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  data:
    mongodb:
      database: ${MONGO_DATABASE:chat_service}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:rootpassword}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
      host: ${MONGO_HOST:localhost}
server:
  port: 8084
