
###

POST http://{{host}}:8081/product
accept: */*
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Pro 1",
    "price": 20,
    "quantity": 20
}


### /order/top-orders-by-date-range

GET http://{{host}}:{{port}}/order/top-orders-by-date-range
Authorization: Bearer {{token}}
Content-Type: application/json
