name: Project Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" , "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install git if missing
        run: if ! which git &> /dev/null; then apt-get update && apt-get install -y git; fi;
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./angular-boilerplate
        run: npm install
      - name: Build
        working-directory: ./angular-boilerplate
        run: npm run build

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
