name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
        with:
          path: ${{ github.workspace }}/angular-boilerplate
      - name: Print release output
        working-directory: ./angular-boilerplate
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}